config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  mount Notifications::Engine => "/notifications"
  devise_for :users, controllers: { registrations: "users/registrations" }

  get 'dashboard', to: 'pages#dashboard', as: :dashboard

  resources :users, only: [:show] do
    resources :businesses, only: %i[new create edit update]
    resources :influencers, only: %i[new create edit update]
  end

  resources :influencers, only: %i[index show edit update]

  resources :businesses, only: %i[edit update index] do
    resources :campaigns, only: %i[new create]
  end

  resources :campaigns, only: %i[index show edit update] do
    resources :proposals, only: %i[new create]
  end

  resources :proposals, only: %i[index show edit update] do
    post "choose_influencers", on: :collection
    resources :reviews, only: %i[new create]
  end

  resources :messages, only: :create
  # resources :chatrooms, only: :show
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :business
  has_many :proposals, dependent: :destroy
  has_many :influencers, through: :proposals
  validates :name, :location, :start_date, :end_date, :description, :budget, presence: true
end

app/models/influencer.rb
class Influencer < ApplicationRecord
  belongs_to :user
  has_many :proposals
  has_many :reviews, through: :proposal

  has_one_attached :photo

  validates :gender, presence: true, inclusion: { in: ['He/Him', 'She/Her', 'They/Them'] }
end

app/controllers/influencers_controller.rb
require_relative '../apis/api_index'

class InfluencersController < ApplicationController
  before_action :set_user, only: %i[new create]
  before_action :find_influencer, only: %i[show edit update]

  def index
    if params[:query].present?
      sql_query = "gender ILIKE :gender OR users.first_name ILIKE :query OR users.last_name ILIKE :query OR users.location ILIKE :query"
      @influencers = Influencer.joins(:user)
                               .where(sql_query, gender: "#{params[:query]}%", query: "%#{params[:query]}%")
    else
      @influencers = Influencer.all
    end
    # fetch proposals without influencer
    @proposals = Proposal.joins(:campaign).where(creator: "Business", campaign: { business: current_user.business, archived: false }).distinct.pluck(:title)

    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: 'influencers/list_influencers', locals: { influencers: @influencers }, formats: [:html] }
    end
  end

  def new
    @influencer = Influencer.new
  end

  def create
    @influencer = Influencer.new(influencer_params)
    @influencer.user = @user
    # @influencer.twitter_followers = TwitterApi.new.twitter_api(influencer_params[:twitter_username])
    # @influencer.ig_followers = InstagramApi.new.instagram_api(influencer_params[:ig_username])
    # @influencer.youtube_subscribers = YoutubeApi.new.youtube_api(influencer_params[:youtube_channel_name])
    # @influencer.facebook_followers = FacebookApi.new.facebook_api(influencer_params[:facebook_username])
    if @influencer.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    @influencer.update!(influencer_params)
    redirect_to user_path(@influencer)
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def find_influencer
    @influencer = Influencer.find(params[:id])
  end

  def influencer_params
    params.require(:influencer).permit(:ig_username, :ig_followers, :youtube_channel_name, :youtube_subscribers,
                                       :twitter_username, :facebook_username, :facebook_followers,
                                       :profile_pic, :gender)
  end
end

app/views/influencers/_card_influencer.html.erb
<div class="card-influencer" data-id="<%= influencer.id %>" data-influencer-target="cards" data-action="click->influencer#toggleDisable">
  <div class="influencer-bar blue-bar d-flex align-items-center">
    <h2><%= influencer.user.first_name %> <%= influencer.user.last_name %> <span class="influencer-gender">(<%= influencer.gender %>)</span></h2>
    <%= cl_image_tag influencer.photo.key, class:"influencer-picture avatar-bordered m-3" if influencer.photo.attached? %>
  </div>
  <div class="influencer-card-info">
    <div class="influencer-descripton d-flex flex-column align-items-start">
      <p><i class="fas fa-map-marker-alt"></i> <%= influencer.user.location %></p>
    </div>
    <div class="d-flex justify-content-between influencer-info" >
      <div class="d-flex flex-column align-items-center">
        <i class="fab fa-instagram card-icon"></i>
        <%= influencer.ig_followers/1000 %>k
      </div>
      <div class="d-flex flex-column align-items-center">
        <i class="fab fa-youtube card-icon"></i>
        <%= influencer.youtube_subscribers/1000 %>k
      </div>
      <div class="d-flex flex-column align-items-center">
        <i class="fab fa-twitter card-icon"></i>
        <%= influencer.twitter_followers/1000 %>k
      </div>
      <div class="d-flex flex-column align-items-center">
        <i class="fab fa-facebook card-icon"></i>
        <%= influencer.facebook_followers/1000 %>k
      </div>
    </div>
  </div>
</div>

app/views/influencers/_form.html.erb
<%= simple_form_for :proposal, url: choose_influencers_proposals_path do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :proposals, collection: @proposals, selected: @proposals.last %>
      <%= f.hidden_field :influencer_ids, as: :array %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Select Influencer", class: "btn btn-form btn-outline-light" %>
    </div>
  <% end %>

app/views/influencers/_list_influencers.html.erb
<div class="card-influencer-container" data-influencer-target="product" data-search-influencers-target="list">
  <% @influencers.each do |influencer| %>
    <%= render "card_influencer", influencer: influencer %>
  <% end %>
</div>

app/views/influencers/_search_bar.html.erb
<div class="form-row">
  <div class="col-4 mb-4">
    <%= form_tag influencers_path, method: :get, data: { search_influencers_target: 'form' } do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Search for Influencers",
        data: { search_influencers_target: 'input',
                action: 'keyup->search-influencers#update' } %>
  </div>
  <div class="form-row mb-4">
    <%= submit_tag "Search", class: "btn-search" %>
    <% end %>
  </div>
</div>

app/views/influencers/edit.html.erb
<div class="container format-login">
  <div class="row justify-content-center">
    <div class="col-xs-6 col-sm-6 col-sm-offset-6">
      <div class="form-login">
        <h2>Update your brand information</h2>
        <%= simple_form_for [@user, @influencer] do |f| %>
          <%= f.error_notification %>

          <div class="form-inputs">
            <%= f.input :ig_username %>
            <%= f.input :ig_followers %>
            <%= f.input :youtube_channel_name %>
            <%= f.input :youtube_subscribers %>
            <%= f.input :twitter_username %>
            <%= f.input :facebook_username %>
            <%= f.input :facebook_followers %>
            <%= f.input :gender, collection: ['Male', 'Female', 'Prefer not to say'] %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, "Update", class: "btn-update" %>
          </div>
        <% end %>
        <strong><%= link_to "Back", :back, class:"btn btn-back btn-outline-light" %></strong>
      </div>
    </div>
  </div>
</div>

app/views/influencers/index.html.erb
<div class="container py-5" data-controller="influencer">
  <div class="d-flex justify-content-between">
    <h1 class="my-5">Influencers</h1>
    <button type="button" class="btn btn-create btn-outline-light my-5" data-influencer-target="btn" data-action="click->influencer#sendProposal" data-id="" data-toggle="modal" data-target="#selectProposalModal">Send Proposal</button>
  </div>
  <div data-controller="search-influencers">
    <%= render "search_bar" %>
    <%= render "list_influencers" %>
  </div>
  <%= render "search_bar" %>
  <div class="d-flex flex-wrap justify-content-between" data-influencer-target="product">
    <% @influencers.each do |influencer| %>
    <div class="card-product" data-id="<%= influencer.id %>" data-influencer-target="cards" data-action="click->influencer#toggleDisable">
      <div class="card-product-infos">
        <h2><%= influencer.user.first_name %>
        <%= influencer.user.last_name %></h2>
        <p><%= influencer.gender %></p>
        <div class="d-inline-flex justify-content-around influencer-info" >
          <div class="d-flex flex-column align-items-center">
            <i class="fab fa-instagram card-icon"></i>
            <%= influencer.ig_followers/1000 %>k
          </div>
          <div class="d-flex flex-column align-items-center">
            <i class="fab fa-youtube card-icon"></i>
            <%= influencer.youtube_subscribers/1000 %>k
          </div>
          <div class="d-flex flex-column align-items-center">
            <i class="fab fa-twitter card-icon"></i>
            <%= influencer.twitter_followers/1000 %>k
          </div>
          <div class="d-flex flex-column align-items-center">
            <i class="fab fa-facebook card-icon"></i>
            <%= influencer.facebook_followers/1000 %>k
          </div>
            <div>
            <p>i</p>
            </div>
        </div>
      </div>
      <%= cl_image_tag influencer.photo.key, class:"avatar-bordered xlarge m-3" %>
    </div>
  <% end %>
</div>
<%= render "./shared/modal_select_influencer", influencer: @influencer, proposals: @proposals, modal_title: "Select an Influencer"%>

app/views/influencers/new.html.erb
<div class="container format-login">
  <div class="row justify-content-center">
    <div class="col-xs-6 col-sm-6 col-sm-offset-6">
      <div class="form-login">
        <h2>Influencer Sign up</h2>
        <%= simple_form_for [@user, @influencer] do |f| %>
          <%= f.error_notification %>

          <div class="form-inputs">
            <%= f.input :ig_username, label: "Instagram Username"  %>
            <%= f.input :youtube_channel_name, label: "YouTube Channel" %>
            <%= f.input :twitter_username %>
            <%= f.input :facebook_username %>
            <%= f.input :gender, collection: ['Male', 'Female', 'Prefer not to say'] %>
            <%= f.input :photo, label: "Profile picture", as: :file %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, "Sign up", class: "btn btn-signup btn-outline-light" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>