config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  mount Notifications::Engine => "/notifications"
  devise_for :users, controllers: { registrations: "users/registrations" }

  get 'dashboard', to: 'pages#dashboard', as: :dashboard

  resources :users, only: [:show] do
    resources :businesses, only: %i[new create edit update]
    resources :influencers, only: %i[new create edit update]
  end

  resources :influencers, only: %i[index show edit update]

  resources :businesses, only: %i[edit update index] do
    resources :campaigns, only: %i[new create]
  end

  resources :campaigns, only: %i[index show edit update] do
    resources :proposals, only: %i[new create]
  end

  resources :proposals, only: %i[index show edit update] do
    post "choose_influencers", on: :collection
    resources :reviews, only: %i[new create]
  end

  resources :messages, only: :create
  # resources :chatrooms, only: :show
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :business, dependent: :destroy
  has_one :influencer, dependent: :destroy
  has_many :proposals
  has_one :business
  has_one :influencer

  validates :phone_number, :first_name, :last_name, :location, presence: true
  validates :role, presence: true, inclusion: { in: %w[Business Influencer] }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  # after_action :after_sign_up_path_for, only: [:create]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    puts 'creating user'
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   attributes = [:phone_number, :first_name, :last_name, :location, :role]
  #   devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
  # end

  # # # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   attributes = [:phone_number, :first_name, :last_name, :location, :role]
  #   devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    p "registrations"
    if resource.save!
      if resource.role == "Influencer"
        new_user_influencer_path(resource)
      elsif resource.role == "Business"
        new_user_business_path(resource)
      end
    else
      render :new
    end
  end

  def after_update_path_for(resource)
    user_path(current_user)
  end

  # def after_inactive_sign_up_path_for(resource)
  #   if resource.role == "Influencer"
  #     new_user_influencer_path(resource)
  #   elsif resource.role == "Business"
  #     new_user_business_path(resource)
  #   end
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/views/users/show.html.erb
<div class="container py-5">
  <h1 class="mt-5 mb-0">Profile</h1>
  <% if current_user.influencer %>
    <div class="d-flex flex-column align-items-center">
      <%= cl_image_tag current_user.influencer.photo.key, :class=> "profile-avatar" if current_user.influencer.photo.attached? %>
      <h3 class="mt-4"><%= @user.first_name %> <%= @user.last_name %></h3>

      <div class="profile-description d-flex">
        <div class="information-card">
          <div class="blue-bar">
            <h4>Personal Information</h4>
          </div>
          <p><i class="fas fa-restroom"></i> <%= @user.influencer.gender %></p>
          <p><i class="fas fa-envelope"></i> <%= @user.email %></p>
          <p><i class="fas fa-map-marked-alt"></i> <%= @user.location.capitalize %></p>
          <p><i class="fas fa-phone-alt"></i> <%= @user.phone_number %></p>
          <%= link_to "Edit", edit_user_registration_path, class: "btn btn-edit btn-outline-light" %>
        </div>

        <div class="information-card">
          <div class="blue-bar">
            <h4>Your Brand</h4>
          </div>
          <p><i class="fab fa-youtube card-icon"></i> <%= @user.influencer.youtube_channel_name %> | <%= @user.influencer.youtube_subscribers/1000 %>k</p>
          <p><i class="fab fa-twitter card-icon"></i> <%= @user.influencer.twitter_username %> | <%= @user.influencer.twitter_followers/1000 %>k</p>
          <p><i class="fab fa-instagram card-icon"></i> <%= @user.influencer.ig_username %> | <%= @user.influencer.ig_followers/1000 %>k</p>
          <p><i class="fab fa-facebook card-icon"></i> <%= @user.influencer.facebook_username %> | <%= @user.influencer.facebook_followers/1000 %>k</p>
          <%= link_to "Edit", edit_user_influencer_path(current_user.influencer.id), class: "btn btn-edit btn-outline-light" %>
        </div>
      </div>
    </div>

  <% elsif current_user.business %>
    <div class="d-flex flex-column align-items-center">
      <%= cl_image_tag current_user.business.photo.key, :class=> "profile-avatar" if current_user.business.photo.attached? %>
      <h3 class="mt-4"><%= @user.business.company_name %></h3>

      <div class="profile-description d-flex">
        <div class="information-card">
          <div class="blue-bar">
            <h4>Personal Information</h4>
          </div>
          <p><i class="fas fa-user-circle"></i> <%= @user.first_name %> <%= @user.last_name %></p>
          <p><i class="fas fa-envelope"></i> <%= @user.email %></p>
          <p><i class="fas fa-phone-alt"></i> <%= @user.phone_number %></p>
          <%= link_to "Edit", edit_user_registration_path, class: "btn btn-edit btn-outline-light" %>
        </div>

        <div class="information-card">
          <div class="blue-bar">
            <h4>Business Information</h4>
          </div>
          <p><i class="fas fa-building"></i> <%= @user.business.company_name %></p>
          <p><i class="fas fa-map-marked-alt"></i> <%= @user.location.capitalize %></p>
          <p><i class="fas fa-link"></i> <%= @user.business.company_url %></p>
          <%= link_to "Edit", edit_business_path(current_user.business.id), class: "btn btn-edit btn-outline-light" %>
        </div>
      </div>
    </div>
  <% end %>
</div>