config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  mount Notifications::Engine => "/notifications"
  devise_for :users, controllers: { registrations: "users/registrations" }

  get 'dashboard', to: 'pages#dashboard', as: :dashboard

  resources :users, only: [:show] do
    resources :businesses, only: %i[new create edit update]
    resources :influencers, only: %i[new create edit update]
  end

  resources :influencers, only: %i[index show edit update]

  resources :businesses, only: %i[edit update index] do
    resources :campaigns, only: %i[new create]
  end

  resources :campaigns, only: %i[index show edit update] do
    resources :proposals, only: %i[new create]
  end

  resources :proposals, only: %i[index show edit update] do
    post "choose_influencers", on: :collection
    resources :reviews, only: %i[new create]
  end

  resources :messages, only: :create
  # resources :chatrooms, only: :show
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_card_proposal.erb
<div class="card-proposal-outer">
  <div class="card-proposal" data-toggle="modal" data-target="#modal-<%= proposal.id %>" >
    <% if partner %>
      <%= cl_image_tag partner.photo.key, class:"avatar-bordered large" if partner.photo.attached?%>
      <h6>
        <% if partner.instance_of? Business %>
          <p><%= partner.company_name %></p>
        <% else %>
          <p>
            <%= partner.user.first_name + ' ' + partner.user.last_name %> <small>(<%= partner.gender %>)</small>
          </p>
        <% end %>
      </h6>
    <% end %>
    <div class="card-proposal-title">
      <p><strong><%= proposal.campaign.name if current_user.role == "Influencer" %></strong></p>
      <p><%= proposal.title %></p>
    </div>
  </div>
  <div class="d-flex">
  <% influencer_condition = proposal.status == "Pending" && partner.instance_of?(Business) && proposal.creator == "Business" %>
  <% business_condition = proposal.status == "Pending" && partner.instance_of?(Influencer) && proposal.creator == "Influencer" %>
  <% if influencer_condition || business_condition %>
    <%= render "proposals/form_accept", proposal: proposal %>
    <%= render "proposals/form_decline", proposal: proposal %>
  <% else %>
    <%= render "proposals/form_mark_as_done", proposal: proposal if proposal.status == "In Progress" && current_user.role == "Influencer" %>
    <%= render "proposals/form_mark_as_paid", proposal: proposal if proposal.status == "Pending Payment" && current_user.role == "Business" %>
    <p class="card-proposal-status"><%= proposal.status %></p>
  <% end %>
  </div>
</div>

app/views/shared/_create_campaign_modal.html.erb
<!-- Create modal -->

  <div class="modal fade" id="createCampaignModal" tabindex="-1" aria-labelledby="createCampaignModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="createCampaignModalLabel"> <%= modal_title %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= render "form", campaign: campaign, business: business %>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_create_proposal_modal.html.erb
<div class="modal fade" id="createProposalModal" tabindex="-1" role="dialog" aria-labelledby="createProposalModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="createProposalModalLabel">Create Collaboration</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'proposals/form', { campaign: @campaign, proposal: @proposal} %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-text">
    <div><a>About Us</a></div>
    <div><a>Contact Us</a></div>
    <div><a>Impressum</a></div>
  </div>
  <div class="footer-brand">
    © InfluenceHorizons
  </div>
</div>

app/views/shared/_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"> <%= modal_title %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render "form", campaign: campaign, business: business %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_create_campaign.html.erb
<!-- Create modal -->

  <div class="modal fade" id="createCampaignModal" tabindex="-1" aria-labelledby="createCampaignModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="createCampaignModalLabel"> <%= modal_title %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= render "form", campaign: campaign, business: business %>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_modal_create_proposal.html.erb
<div class="modal fade" id="createProposalModal" tabindex="-1" role="dialog" aria-labelledby="createProposalModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="createProposalModalLabel">Create Collaboration</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'proposals/form', { campaign: @campaign, proposal: @proposal } %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_select_influencer.html.erb
<!-- Create modal -->

  <div class="modal fade" id="selectProposalModal" tabindex="-1" aria-labelledby="selectProposalModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="selectProposalModalLabel"> <%= modal_title %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
        <%= render 'influencers/form', { proposal: @proposal, influencer: @influencer } %>
          <%# form with proposals without influencers as dropdown %>
          <%# form should have hidden_field with influencer IDs %>
          <%# user will select one proposal and click submit %>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_modal_show_proposal.html.erb
<div class="modal fade" id="modal-<%= proposal.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog <%= 'modal-xl' unless proposal.status == "Pending" || proposal.status == "Declined" %>" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"> <%= proposal.title %> </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="d-flex justify-content-between">
          <div>
            <div class="d-flex">
              <i class="pt-1 far fa-comment-dots"></i>
              <div class="ml-1">
                <p class="m-0"><strong><%= proposal.campaign.name %></strong></p>
                <p><%= proposal.campaign.description %></p>
              </div>
            </div>
            <p><i class="fas fa-info-circle"></i> <%= proposal.status %></p>
            <p><i class="far fa-calendar-alt"></i> <%= proposal.campaign.start_date.strftime("%e %b %Y") %> - <%= proposal.campaign.end_date.strftime("%e %b %Y") %></p>
          </div>
          <div class="d-flex flex-column justify-content-end align-items-center text-center">
            <% if partner %>
              <%= cl_image_tag partner.photo.key, class:"avatar-bordered large" if partner.photo.attached? %>
              <% if partner.instance_of? Business %>
                <p><%= partner.company_name %></p>
              <% else %>
                <p><%= partner.user.first_name + ' ' + partner.user.last_name %></p>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <% unless proposal.status == "Pending" || proposal.status == "Declined" %>
        <div class="modal-body border-top">
          <div class="d-flex justify-content-between">
            <%= render 'proposals/chatroom', chatroom: proposal.chatroom, message: @message, partner: partner %>
          </div>
        </div>
      <% end %>
        <% influencer_condition = proposal.status == "Pending" && partner.instance_of?(Business) && proposal.creator == "Business" %>
        <% business_condition = proposal.status == "Pending" && partner.instance_of?(Influencer) && proposal.creator == "Influencer" %>
        <% if influencer_condition || business_condition %>
          <div class="modal-footer">
            <%= render "proposals/form_accept", proposal: proposal %>
            <%= render "proposals/form_decline", proposal: proposal %>
          </div>
        <% end %>
        <% if proposal.status == "In Progress" && current_user.role == "Influencer" %>
          <div class="modal-footer">
            <%= render "proposals/form_mark_as_done", proposal: proposal %>
          </div>
        <% end %>
        <% if proposal.status == "Pending Payment" && current_user.role == "Business" %>
          <div class="modal-footer">
            <%= render "proposals/form_mark_as_paid", proposal: proposal %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% if current_page?(main_app.root_path)%>
  <div class="navbar navbar-expand-sm navbar-lewagon fixed-top" data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
  <%= link_to main_app.root_path, class: "navbar-brand" do %>
    <%# <img src="https://res.cloudinary.com/katielht/image/upload/v1637870614/Logo_IH_OhneSlogan_ccqxey.png"> %>
  <% end %>
<% else %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-lewagon-blue fixed-top">
  <%= link_to main_app.root_path, class: "navbar-brand" do %>
    <h3 style="padding: 4px 0 0 8px; color: white;">InfluenceHorizons</h3>
    <%# <img src="https://res.cloudinary.com/katielht/image/upload/v1637870614/Logo_IH_OhneSlogan_ccqxey.png"> %>
  <% end %>
<% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to notifications_path, class:"nav-link d-flex justify-content-between" do %>
            <i class="fas fa-bell"></i>
            <% if !Notification.unread_count(current_user).zero? %>
              <div class="batch"><%= Notification.unread_count(current_user) %></div>
            <% end %>
          <% end %>
        </li>

        <li class="nav-item dropdown d-flex align-items-center">
          <p class="my-0 mr-2">Welcome, <%= current_user.first_name %></p>
          <% if current_user.influencer %>
            <%= cl_image_tag current_user.influencer.photo.key, class:"avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false if current_user.influencer.photo.attached? %>
          <% elsif current_user.business %>
            <%= cl_image_tag current_user.business.photo.key, class:"avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false if current_user.business.photo.attached? %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", main_app.dashboard_path, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<% if user_signed_in? && current_user.business %>
  <a><i class="fas fa-angle-left" data-action="click->side-bar#toggle" data-side-bar-target="button"></i></a>
  <div>
    <div id="mySidebar" class="sidebar" data-side-bar-target="sidebar">
      <%= link_to "Statistics", main_app.dashboard_path, class: "#{'active' if current_page?(main_app.dashboard_path)}" %>
      <%= link_to "Campaigns", main_app.campaigns_path, class: "#{'active' if current_page?(main_app.campaigns_path) || request.fullpath.start_with?('/campaigns/')}" %>
      <%= link_to "Influencers", main_app.influencers_path, class: "#{'active' if current_page?(main_app.influencers_path)}" %>
      <%#= link_to "Reviews", reviews_path %>
      <%= link_to "Profile", main_app.user_path(current_user), class: "#{'active' if current_page?(main_app.user_path(current_user))}" %>
      <%= link_to "Log out", main_app.destroy_user_session_path, method: :delete, class: "sign-out-btn text-center" %>
    </div>
  </div>
<% elsif user_signed_in? && current_user.influencer %>
  <a><i class="fas fa-angle-left" data-action="click->side-bar#toggle" data-side-bar-target="button"></i></a>
  <div>
    <div id="mySidebar" class="sidebar" data-side-bar-target="sidebar">
      <%= link_to "Statistics", main_app.dashboard_path, class: "#{'active' if current_page?(main_app.dashboard_path)}" %>
      <%= link_to "Collaborations", main_app.proposals_path, class: "#{'active' if current_page?(main_app.proposals_path)}"   %>
      <%= link_to "Campaigns", main_app.campaigns_path, class: "#{'active' if current_page?(main_app.campaigns_path) || request.fullpath.start_with?('/campaigns/')}" %>
      <%#= link_to "Reviews", reviews_path %>
      <%= link_to "Profile", main_app.user_path(current_user), class: "#{'active' if current_page?(main_app.user_path(current_user))}"  %>
      <%= link_to "Log out", main_app.destroy_user_session_path, method: :delete, class: "sign-out-btn text-center" %>
    </div>
  </div>
<% end %>

app/views/shared/_tab_collaborations.html.erb
<%if @proposals.size == 0 %>
  <div class="d-flex justify-content-between">
    <h4>You have no active collaborations</h4>
    <button type="button" class="btn btn-create btn-outline-light" data-toggle="modal" data-target="#createProposalModal" style="margin-bottom: 30px">Create Collaboration</button>
  </div>
<%else%>
  <% unless @proposals.first.campaign.archived %>
    <div class="d-flex justify-content-end">
      <button type="button" class="btn btn-create btn-outline-light" data-toggle="modal" data-target="#createProposalModal" style="margin-bottom: 30px">Create Collaboration</button>
    </div>
  <% end %>

  <div class="proposals-group" data-controller="dropdown">
    <div class="dropdown-header">
      <h4>Open</h4>
      <div class="dropdown-btn fas fa-caret-up" data-dropdown-target="btn" data-action="click->dropdown#toggleContent"></div>
    </div>
    <div class="card-container" data-dropdown-target="container">
      <% @proposals.each do |proposal| %>
        <% if proposal.accepted && proposal.status != "Completed" %>
          <%= render "./shared/modal_show_proposal", proposal: proposal, partner: proposal.influencer, modal_title: proposal.title %>
          <%= render "./shared/card_proposal", proposal: proposal, partner: proposal.influencer %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="proposals-group" data-controller="dropdown">
    <div class="dropdown-header">
      <h4>Pending</h4>
      <div class="dropdown-btn fas fa-caret-up" data-dropdown-target="btn" data-action="click->dropdown#toggleContent"></div>
    </div>
    <div class="card-container" data-dropdown-target="container">
      <% @proposals.each do |proposal| %>
        <% if proposal.status == "Pending" && proposal.creator == "Business" %>
          <%= render "./shared/modal_show_proposal", proposal: proposal, partner: proposal.influencer, modal_title: proposal.title %>
          <%= render "./shared/card_proposal", proposal: proposal, partner: proposal.influencer %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="proposals-group" data-controller="dropdown">
    <div class="dropdown-header">
      <h4>Closed</h4>
      <div class="dropdown-btn fas fa-caret-up" data-dropdown-target="btn" data-action="click->dropdown#toggleContent"></div>
    </div>
    <div class="card-container" data-dropdown-target="container">
      <% @proposals.each do |proposal| %>
        <% if (proposal.accepted && proposal.status == "Completed") || proposal.status == "Declined" %>
          <%= render "./shared/modal_show_proposal", proposal: proposal, partner: proposal.influencer, modal_title: proposal.title %>
          <%= render "./shared/card_proposal", proposal: proposal, partner: proposal.influencer %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>
<%= render "./shared/modal_create_proposal", campaign: @campaign, business: @business, modal_title: "Create a Campaign" %>

app/views/shared/_tab_details.html.erb
<div class="details">

  <% if current_user.business %>
    <div class="campaign-status">
      <% if @campaign.visibility == true %>
        <p>Public visibility: <strong>Activated</strong></p>
      <% else %>
        <p>Public visibility: <strong>Deactivated</strong></p>
      <% end %>
    </div>
  <% end %>

  <div class="row m-0">
    <div class="col card-info campaign-card-info">
      <div class="blue-bar">
        <h4>Location</h4>
      </div>
      <div class="center-content mt-3">
        <i class="fas fa-map-marker-alt"></i>
        <p><%= @campaign.location %></p>
      </div>
    </div>

    <div class="col card-info campaign-card-info">
      <div class="blue-bar">
        <h4>Dates</h4>
      </div>
      <i class="fas fa-calendar-alt"></i>
      <p class="campaign-card-small-text"><strong><%= @campaign.start_date.strftime("%e %b %Y") %>
      <br>
      </strong> to <strong>
      <br>
      <%= @campaign.end_date.strftime("%e %b %Y") %></strong></p>
    </div>

    <% if current_user.business %>
      <div class="col card-info campaign-card-info">
        <div class="blue-bar">
          <h4>Budget</h4>
        </div>
        <div class="center-content mt-3">
          <i class="fas fa-wallet"></i>
          <p>£ <%= @campaign.budget %></p> <!--hide on influencer -->
        </div>
      </div>
    <% end %>
  </div>

  <div class="card-info large-details-card">
    <div class="description">
      <div class="blue-bar">
        <h4>Description</h4>
      </div>
      <p><%= @campaign.description %></p>
    </div>
  </div>

  <% if current_user.business %>
    <div class="card-info large-details-card">
      <h4 class="blue-bar">Uploaded Documents</h4>
    </div>
  <% end %>

</div>