config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  mount Notifications::Engine => "/notifications"
  devise_for :users, controllers: { registrations: "users/registrations" }

  get 'dashboard', to: 'pages#dashboard', as: :dashboard

  resources :users, only: [:show] do
    resources :businesses, only: %i[new create edit update]
    resources :influencers, only: %i[new create edit update]
  end

  resources :influencers, only: %i[index show edit update]

  resources :businesses, only: %i[edit update index] do
    resources :campaigns, only: %i[new create]
  end

  resources :campaigns, only: %i[index show edit update] do
    resources :proposals, only: %i[new create]
  end

  resources :proposals, only: %i[index show edit update] do
    post "choose_influencers", on: :collection
    resources :reviews, only: %i[new create]
  end

  resources :messages, only: :create
  # resources :chatrooms, only: :show
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :campaign
  belongs_to :influencer, optional: true
  has_one :chatroom
  has_many :reviews, dependent: :destroy
  validates :title, :creator, presence: true

  after_commit :incoming_notifications, on: :create
  after_commit :update_notifications, on: :update

  private

  def incoming_notifications
    if creator == "Influencer"
      Notification.create(
        notify_type: 'incoming',
        actor: influencer.user,
        user: campaign.business.user,
        target: self,
        second_target: campaign
      )
    elsif creator == "Business" && influencer
      Notification.create(
        notify_type: 'incoming',
        actor: campaign.business.user,
        user: influencer.user,
        target: self,
        second_target: campaign
      )
    end
  end

  def update_notifications
    if status == "Pending" && creator == "Business"
      Notification.create(
        notify_type: 'incoming',
        actor: campaign.business.user,
        user: influencer.user,
        target: self,
        second_target: campaign
      )
    elsif status == "Declined" && accepted == false
      Notification.create(
        notify_type: 'declined',
        actor: creator == "Business" ? influencer.user : campaign.business.user,
        user: creator == "Business" ? campaign.business.user : influencer.user,
        target: self,
        second_target: campaign
      )
    elsif status == "In Progress" && accepted == true
      Notification.create(
        notify_type: 'accepted',
        actor: creator == "Business" ? influencer.user : campaign.business.user,
        user: creator == "Business" ? campaign.business.user : influencer.user,
        target: self,
        second_target: campaign
      )
    elsif status == "Pending Payment" && accepted == true
      Notification.create(
        notify_type: 'markdone',
        actor: influencer.user,
        user: campaign.business.user,
        target: self,
        second_target: campaign
      )
    elsif status == "Completed" && accepted == true
      Notification.create(
        notify_type: 'markpaid',
        actor: campaign.business.user,
        user: influencer.user,
        target: self,
        second_target: campaign
      )
    end
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :set_campaign, only: [:create]
  before_action :find_proposal, only: %i[show edit update]

  def index
    if current_user.role == 'Influencer'
      @influencer = current_user.influencer
      @proposals = @influencer.proposals
      @message = Message.new
    end
  end

  def choose_influencers
    @proposal = Proposal.where(title: params[:proposal][:proposals])[0]
    # @influencers = Influencer.find(params[:proposal][:influencer_ids])
    params[:proposal][:influencer_ids].split(",").each do |id|
      if @proposal.influencer.nil?
        @proposal.update(influencer_id: id)
      else
        @new_proposal = Proposal.new(title: @proposal.title, status: @proposal.status, campaign: @proposal.campaign, influencer_id: id, creator: @proposal.creator )
        @new_proposal.save!
        @chatroom = Chatroom.create!(name: @new_proposal.title, proposal: @new_proposal)
      end
    end
    redirect_to campaign_path(@proposal.campaign)
  end

  def create
    @proposal = Proposal.new(proposal_params)
    @proposal.campaign = @campaign
    @proposal.creator = current_user.role
    @proposal.influencer = current_user.influencer if current_user.role == "Influencer"
    if @proposal.save!
      @chatroom = Chatroom.create!(name: @proposal.title, proposal: @proposal)
      redirect_to current_user.role == "Business" ? influencers_path : proposals_path
    else
      @proposals = @campaign.proposals.where(creator: "Business")
      @incoming_proposals = @campaign.proposals.where(creator: "Influencer")
      render 'campaigns/show'
    end
  end

  def show; end

  def update
    @proposal.update(proposal_params)
    if current_user.role == "Business"
      redirect_to campaign_path(@proposal.campaign)
    else
      redirect_to proposals_path
    end
  end

  private

  def set_campaign
    @campaign = Campaign.find(params[:campaign_id])
  end

  def find_proposal
    @proposal = Proposal.find(params[:id])
  end

  def proposal_params
    params.require(:proposal).permit(:title, :status, :accepted)
  end
end

app/views/proposals/_chatroom.html.erb
<div id="chatroom-<%= chatroom.id %>" class="container chatroom" data-controller="chatroom-subscription"
     data-chatroom-subscription-chatroom-id-value="<%= chatroom.id %>"
     data-chatroom-subscription-proposal-id-value="<%= chatroom.proposal.id %>"
     data-chatroom-subscription-current-user-id-value="<%= current_user.id %>"
     data-chatroom-subscription-target="chatroom">
  <div class="messages" data-chatroom-subscription-target="messages">
    <% chatroom.messages.each do |message| %>
      <%= render "messages/message", message: message, partner: partner %>
    <% end %>
  </div>
  <% unless chatroom.proposal.status == "Completed" %>
    <%= simple_form_for(@message, remote: true, style:"background-color: white;") do |f| %>
      <%= f.hidden_field :chatroom_id, value: chatroom.id %>
      <div class="d-flex">
        <%= f.input :content, label: false, placeholder: "Message ", input_html: { data: { chatroom_subscription_target: "input" } } %>
        <%= f.submit class:'btn btn-create m-0' %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/proposals/_form.html.erb
<%= simple_form_for [campaign, proposal] do |f|%>
  <p>Detail your proposal:</p>
  <%= f.text_area :title, placeholder: "#Need a post on instagram", class:"w-100 py-1 px-2" %>
  <%= f.submit current_user.role == "Business" ? "Look for potential influencers" : "Create Collaboration", class:"btn btn-form btn-outline-light" %>
<% end %>

app/views/proposals/_form_accept.html.erb
<%= simple_form_for (proposal) do |f| %>
  <%= f.hidden_field :accepted, value: true %>
  <%= f.hidden_field :status, value: "In Progress" %>
  <%= f.submit "Accept", class:"btn card-proposal-status accept" %>
<% end %>

app/views/proposals/_form_decline.html.erb
<%= simple_form_for (proposal) do |f| %>
  <%= f.hidden_field :accepted, value: false %>
  <%= f.hidden_field :status, value: "Declined" %>
  <%= f.submit "Decline", class:"btn card-proposal-status decline" %>
<% end %>

app/views/proposals/_form_mark_as_done.html.erb
<%= simple_form_for (proposal) do |f| %>
  <%= f.hidden_field :status, value: "Pending Payment" %>
  <%= f.submit "Mark as done", class:"btn card-proposal-status mark-as-done" %>
<% end %>

app/views/proposals/_form_mark_as_paid.html.erb
<%= simple_form_for (proposal) do |f| %>
  <%= f.hidden_field :status, value: "Completed" %>
  <%= f.submit "Mark as paid", class:"btn card-proposal-status mark-as-paid" %>
<% end %>

app/views/proposals/index.html.erb
<div class="container py-5">
  <h1 class="my-5">Collaborations Overview</h1>
  <%if @proposals.size == 0 %>
    <div class="d-flex justify-content-between">
      <h4 class="my-5">You have no active collaborations</h4>
      <%= link_to "Find campaigns", campaigns_path, class:"btn btn-create my-5" %>
    </div>
  <%else%>
    <div class="proposals-group" data-controller="dropdown">
      <div class="dropdown-header">
        <h4>Open</h4>
        <div class="dropdown-btn fas fa-caret-up" data-dropdown-target="btn" data-action="click->dropdown#toggleContent"></div>
      </div>
      <div class="card-container" data-dropdown-target="container">
        <% @proposals.each do |proposal| %>
          <% if proposal.accepted && proposal.status != "Completed" %>
            <%= render "./shared/modal_show_proposal", proposal: proposal, partner: proposal.campaign.business, modal_title: proposal.title %>
            <%= render "./shared/card_proposal", proposal: proposal, partner: proposal.campaign.business %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="proposals-group" data-controller="dropdown">
      <div class="dropdown-header">
        <h4>Pending</h4>
        <div class="dropdown-btn fas fa-caret-up" data-dropdown-target="btn" data-action="click->dropdown#toggleContent"></div>
      </div>
      <div class="card-container" data-dropdown-target="container">
        <% @proposals.each do |proposal| %>
          <% if proposal.status == "Pending" %>
            <%= render "./shared/modal_show_proposal", proposal: proposal, partner: proposal.campaign.business, modal_title: proposal.title %>
            <%= render "./shared/card_proposal", proposal: proposal, partner: proposal.campaign.business %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="proposals-group" data-controller="dropdown">
      <div class="dropdown-header">
        <h4>Closed</h4>
        <div class="dropdown-btn fas fa-caret-up" data-dropdown-target="btn" data-action="click->dropdown#toggleContent"></div>
      </div>
      <div class="card-container" data-dropdown-target="container">
        <% @proposals.each do |proposal| %>
          <% if (proposal.accepted && proposal.status == "Completed") || proposal.status == "Declined" %>
            <%= render "./shared/modal_show_proposal", proposal: proposal, partner: proposal.campaign.business, modal_title: proposal.title %>
            <%= render "./shared/card_proposal", proposal: proposal, partner: proposal.campaign.business %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>